name: BuildApplication
on:
  push:
    branches:
      - master

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # JDKのセットアップ
      - name: set up JDK 11
        uses: actions/setup-java@v3.9.0
        with:
          distribution: 'zulu'
          java-version: '11'
      
      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      
      - name: Build
        run: | 
            ./gradlew assembleDebug
      
      - name: Upload
        uses: actions/upload-artifact@v3
        if: ${{ success() }}
        with:
          name: application
          path: app/build/outputs

